return {
  "neovim/nvim-lspconfig",
  config = function()
    require'lspconfig'.ocamlls.setup{}
    require'lspconfig'.terraformls.setup{}
    require'lspconfig'.tsserver.setup{}
    require'lspconfig'.vimls.setup{}
    require'lspconfig'.yamlls.setup{}
    require'lspconfig'.jsonls.setup{}
    require'lspconfig'.bashls.setup{}
    require'lspconfig'.dockerls.setup{}
    require'lspconfig'.html.setup{}
    require'lspconfig'.cssls.setup{}
    require'lspconfig'.pyright.setup{}
    require'lspconfig'.rust_analyzer.setup{}
    require'lspconfig'.gopls.setup{}
    require'lspconfig'.clangd.setup{}
    require'lspconfig'.ccls.setup{}
    require'lspconfig'.jdtls.setup{}
    require'lspconfig'.vuels.setup{}
    require'lspconfig'.svelte.setup{}
    require'lspconfig'.graphql.setup{}
    require'lspconfig'.hls.setup{}
    require'lspconfig'.elixirls.setup{}
    require'lspconfig'.clojure_lsp.setup{}
    require'lspconfig'.nimls.setup{}
    require'lspconfig'.phpactor.setup{}
    require'lspconfig'.elmls.setup{}
  end
}
